# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd09099af5e4e5390e941021d0ce1315c48152bc18c60c3967ccae99877a8734270a58935a4046b2bfc1d83001856f558b993af73400a6127600f4fed3f2b8eb

test:
  secret_key_base: 159d4bc4261ed76453354e8d2616e9d8bf9c4ecacd67c5d0d7e702a51da25b4d0c7b894c1a58db27047cdabaf7194dbcf121bf01250eb799a50a5812336c14ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
